---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "backup-exporter.labels" . | nindent 4 }}
type: opaque
data:
  S3_ADDRESS: {{ .Values.env.s3_address | b64enc | quote }}
  S3_BUCKET: {{ .Values.env.s3_bucket | b64enc | quote }}
  S3_ACCESS_KEY: {{ .Values.env.s3_access_key | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.env.s3_secret_key | b64enc | quote }}
  S3_EXCLUDE_DIRS: {{ .Values.env.s3_exclude_dirs | b64enc | quote }}
